edition = "2021"
force_explicit_abi = true
hard_tabs = false
max_width = 100
merge_derives = true
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
