[package]
name = "a2voice"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
teloxide = { version = "0.15.0", features = ["macros"] }
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros", "sync"] }