[package]
name = "a2voice"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
teloxide = { version = "0.12.2", features = ["macros"] }
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros", "sync"] }
